# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit autoupdate
repos:
  # pre-commit-hooks supplies a multitude of small hooks
  # To get an overview of them all as well as the ones used here, please see
  # https://github.com/pre-commit/pre-commit-hooks#hooks-available
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-toml
      name: Check TOML
    - id: check-yaml
      name: Check YAML
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
      exclude: ^CHANGELOG.md$
    - id: name-tests-test
      args: ["--pytest-test-first"]
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

  # Black is a code style and formatter
  # It works on files in-place
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
    - id: black

  # Ruff is a code style and formatter
  # It works on files in-place
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    - id: ruff
      args:
        - --fix
        - --show-fixes

  # Pyupgrade is a code upgrade tool
  # It works on files in-place
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
    - id: pyupgrade
      args: [--py310-plus]

  # Bandit is a security linter
  # More information can be found in its documentation:
  # https://bandit.readthedocs.io/en/latest/
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
    - id: bandit
      args: ["-r"]
      exclude: ^(tests|docs/example|.github/utils)/.*$

  # mypy is a static typing linter
  # The main code repository can be found at:
  # https://github.com/python/mypy
  # The project's documentation can be found at:
  # https://mypy.readthedocs.io/en/stable/index.html
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    - id: mypy
      exclude: ^(docs/example|tests)/.*$
      additional_dependencies:
        - pydantic>=2
        - types-requests
        - types-pyyaml
      args: [--explicit-package-bases]
