version: "3"

services:
  entities_service:
    build:
      context: "."
      target: "${ENTITIES_SERVICE_DOCKER_TARGET:-development}"
    ports:
      - "${ENTITIES_SERVICE_PORT:-8000}:80"
    environment:
      PORT: ${ENTITIES_SERVICE_PORT:-8000}
      ENTITIES_SERVICE_BASE_URL: "${ENTITIES_SERVICE_HOST:-http://onto-ns.com/meta}"
      ENTITIES_SERVICE_MONGO_URI: "mongodb://mongodb:27017"
      ENTITIES_SERVICE_MONGO_USER: ${MONGO_USER:-root}
      ENTITIES_SERVICE_MONGO_PASSWORD: ${MONGO_PASSWORD:-root}
    depends_on:
      - mongodb
    networks:
      - entities_service_net
    volumes:
      - "${PWD}:/app"

  mongodb:
    image: mongo:7
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-root}
    networks:
      - entities_service_net

networks:
  entities_service_net:
